# Generated by Django 4.2.2 on 2023-06-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
